services:
  app:
    build: .
    network_mode: host
    environment:
      - DATABASE_URL=host=127.0.0.1 port=5433 user=sameer password=Sameer@123 dbname=filetransfer sslmode=disable
    volumes:
      - ./downloads_docker_1:/app/downloads
    depends_on:
      db:
        condition: service_healthy
    restart: always

  app2:
    build: .
    network_mode: host
    command: [ "./filetransfer", "-web", "8081", "-transfer", "9002", "-name", "Peer-2" ]
    environment:
      - DATABASE_URL=host=127.0.0.1 port=5434 user=sameer password=Sameer@123 dbname=filetransfer sslmode=disable
    volumes:
      - ./downloads_docker_2:/app/downloads
    depends_on:
      db2:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=sameer
      - POSTGRES_PASSWORD=Sameer@123
      - POSTGRES_DB=filetransfer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_1:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sameer -d filetransfer" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  db2:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=sameer
      - POSTGRES_PASSWORD=Sameer@123
      - POSTGRES_DB=filetransfer
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sameer -d filetransfer" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data_1:
  postgres_data_2:
